### ISSUE TITLE
Update to vite

### ISSUE THREAD

**Issue by mikhi32** [Ladvace/SvelteKit-Portfolio#1]
Sveltekit dev is deprecated. Move to vite?

**Comment by Ladvace** [comment]
where did you read that it's deprecated? Anyway as soon as I have time I'm gonna rewrite from scratch my portfolio

**Comment by mikhi32** [comment]
If you try to run

```npm run dev```
It gives you an error. Also vite 2 is deprecated

**Comment by Ladvace** [comment]
yeah I know, I will try to update them in the weekend

**Comment by mikhi32** [comment]
Ok!

**Comment by Ladvace** [comment]
ok updated, Thanks for reminding me that!
