### ISSUE TITLE
Route are not working says 404

### ISSUE THREAD

**Issue by bobiafk** [Ladvace/SvelteKit-Portfolio#2]

**Comment by Ladvace** [comment]
a specific route or all the routes?

**Comment by mrtkp9993** [comment]
> a specific route or all the routes?

All routes other than home are 404.

**Comment by Ladvace** [comment]
Thanks for reporting the error, I'll try working on it this weekend

**Comment by Ladvace** [comment]
it should be fixed, updated to the last routing system, as soon as I have time I'll improve it

**Comment by Ladvace** [comment]
if closed feel free to close the issue
